openapi: 3.0.0
info:
  title: "Sorter"
  description: "Takes two operands, returns -1, 0, or 1"
  version: "0.0.0"
  contact:
    email: "christrahey@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "example.com/some_mount_point:port"
  - description: Clients SHUOLD treat the url as an opaque value.
tags:
- name: "SOLID"
  description: "Guided by best-practice OOP design principles"
  externalDocs:
    description: "Learn more about SOLID"
    url: "https://en.wikipedia.org/wiki/SOLID"
paths:
  /sort/{lhs}/{rhs}:
    get:
      summary: "Sort"
      operationId: sort
      parameters:
      - in: "path"
        name: "lhs"
        description: "Left-hand-side. If this is the greater value, returns 1"
        required: true
        schema:
          $ref: "#/definitions/string"
      - in: "path"
        name: "rhs"
        description: "Right-hand-side. If this is the greater value, returns -1"
        required: true
        schema:
          $ref: "#/definitions/string"
      responses:
        404:
          description: "The queue does not exist and could not be created"
        201:
          description: "The item was added successfully"
  /{queue}/checkout:
    post:
      summary: "(semi) Pop an item from the front of the queue. The item will automatically return to the queue after a timeout if /commit is not called soon!"
      parameters:
      - in: "path"
        name: "queue"
        description: "This server may manage multiple queues. Clients can specify."
        required: true
      requestBody:
        description: Metadata for the checkout. Not currently used but may in the future contain e.g. expected time to completion.
        required: False
        content:
          application/json
      responses:
        201:
          description: "The checkout was successful."
      operationId: "checkout"
