openapi: 3.0.0
info:
  title: "Pattern Matching"
  description: "A hash map of patterns to values, retrieve values via a string that matches the corresponding pattern"
  version: "0.0.0"
  contact:
    email: "christrahey@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "example.com/some_mount_point:port"
  - description: Clients SHUOLD treat the url as an opaque value.
  @todo: Include a sorter service at call-time
tags:
- name: "SOLID"
  description: "Guided by best-practice OOP design principles"
  externalDocs:
    description: "Learn more about SOLID"
    url: "https://en.wikipedia.org/wiki/SOLID"
paths:
  /pattern/match/{subject}:
    get:
      summary: "Retrieve the current value of {key} in this cache"
      operationId: get
      parameters:
      - in: "path"
        name: "subject"
        description: "The subject to test. URL-safe Base64-encoded."
        required: true
        schema:
          $ref: "#/definitions/b64string"
      responses:
        404:
          description: "That key does not exist in this cache"
        200:
          description: "Response body is the value retrieved from the cache"
  /patterns:
    post:
      summary: "Store a value associated with the provided patterns"
      requestBody:
        description: A JSON object with two keys, `patterns` stores a list of strings and `value` stores any serializable 
        required: True
        content:
          application/octet-stream
            schema:
            type: any
      responses:
        200:
          description: "The value has been stored"
      operationId: "set"
