openapi: 3.0.0
info:
  title: Economic Entities
  description: >
    A service to resolve economic identity identifiers to more pertinent details about them.
  version: 0.0.1
components:
  schemas:
    EconomicEntityIdentifier:
      type: string
      format: uri
    EconomicEntity:
      parameters:
        title:
          type: string
        entity_type:
          type: string
          description: 
  parameters:
    JournalEntry:
      - in: path
        name: entry
        schema:
          type: string
          format: uuid
        required: true
        description: UUID of the Journal Entry
    Since:
      - in: query
        name: since
        schema:
          type: string
          format: date-time
        required: false
        description: Exclude any entries prior to provided date.
    After:
      - in: query
        name: after
        schema:
          type: string
          format: uuid
        required: false
        description: Exclude any entries prior to the entry referred to by uuid

paths:
  /entity/{entity}
    get:
      summary: An Economic Entity
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EconomicEntity'
    post:
      summary: Post an entry to this entity's journal
      requestBody:
        description: A journal entry
        required: true
        content:
          application/json:
            schema:
              $ref: '#/componenets/scemas/JournalEntry'
      responses:
        '201':
          description: Created. Entry successfully journaled. Response inludes newly minted uuid.
          content:
            application/json:
              schema:
                $ref '#/components/schemas/JournalEntry'
        '400':
          description: Bad Request. Request is malformed or could not be understood
        '409':
          description: Conflict. Debits do not equal Credits
        '404':
          description: Economic Entity not found
    
  /{entity}/journal/entry/{entry_id}:
    get:
      summary: An individual journal entry
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JournalEntry'
        '404':
          description: That entry could not be found

